// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaswsgzvbyqiotbzcjfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhc3dzZ3p2YnlxaW90YnpjamZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjE0MjIsImV4cCI6MjA3MDM5NzQyMn0.77jsSxfOd6G_cUi_MFYLoXerCRDSEqjFLW9SuAc11CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});